#!/bin/bash
#SBATCH --job-name=passive_model
#SBATCH --ntasks=16
#SBATCH --partition=compute
#SBATCH --mem-per-cpu=4g
#SBATCH --time=1-0:0:0

module use /apps/unit/DeSchutterU/.modulefiles
module load steps/2022_10_15_443f10b_special

mpirun -n $SLURM_NPROCS python3 local_final.py
